config/routes.rb
Rails.application.routes.draw do
  resources :widgets

	root to: 'home#index'
	devise_for :users, :controllers => { :omniauth_callbacks => 'users/omniauth_callbacks' }
	resources :contacts
	resources :thermometers do
		resources :readings
		end
  resources :home

	get '/bootstrap' => 'bootstrap#index'

end

app/models/thermometer.rb
class Thermometer < ActiveRecord::Base
	belongs_to :user
	has_many :readings
	after_create :get_reading
	# validates_associated :users
	# scope :broken (where ('thermometers_updated_at < 300'))
	# self.inheritance_column = :temperature


	def get_reading
		uri = URI.parse('http://localhost:5000/thermometers.json')
		thermo_response = Net::HTTP.get_response(uri)
		check = thermo_response.body
		j = JSON.parse(check)
	end

	def mail_deliver
		# @thermometer_server = Thermometer.find(params[:id])
		ThermometerMailer.delay.thermo_confirmation(self)
	end

	def max_violation?
		@thermometer=Thermometer.last
		if self.temperature > @thermometer.max_temp
			puts "yes!!!" * 100
			ThermometerMailer.thermo_max_violation(@thermometer).deliver
		end
	end


	def self.import(file)
  spreadsheet = open_spreadsheet(file)
  header = spreadsheet.row(1)
  (2..spreadsheet.last_row).each do |i|
    row = Hash[[header, spreadsheet.row(i)].transpose]
    product = find_by_id(row["id"]) || new
    product.attributes = row.to_hash.slice(*accessible_attributes)
    product.save!
  		end
	end

def self.open_spreadsheet(file)
  case File.extname(file.original_filename)
  when ".csv" then Csv.new(file.path, nil, :ignore)
  when ".xls" then Excel.new(file.path, nil, :ignore)
  when ".xlsx" then Excelx.new(file.path, nil, :ignore)
  else raise "Unknown file type: #{file.original_filename}"
  end
end
end

app/controllers/thermometers_controller.rb
class ThermometersController < ApplicationController
	include ActionController::Live
  before_action :set_thermometer, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!
	require 'rake'
	Rake::Task.clear # necessary to avoid tasks being loaded several times in dev mode
	DeviseDemo::Application.load_tasks # providing your application name is 'sample'

	# def stream
	# 	response.headers['Content-Type'] = 'text/event-stream'
	# 	100.times {
	# 		response.stream.write "hello world\n"
	# 		sleep 1
	# 	}
	# ensure
	# 	response.stream.close
	# end

	# def hello
	# 	puts "hello" *50
	# end

  # def mass_update
  #   # Thermometer.update(params[:thermometers].keys, params[:thermometers].values])
  #   # if thermometer_server.valid?
  #   #   redirect_to temperatures_path
  #   # else
  #   #   render 'edit'
  #   # end
  #   temperature = Thermometer.find(params[:id])
  #   if temperature.update(params[:temperatures])
  #     redirect_to temperatures_path
  #   else
  #     render 'edit'
  #   end
  # end

  # def thermometer_off
  #   temperature = Thermometer.find(params[:id])
  #   if temperature.toggle
  #     redirect_to temperatures_path
  #   end
  # end

  # def email_alert_high_temp
		# # Reading.thermo_respons.parse()
  #   if Reading.thermo_response[0] >  @thermometer.max_rule
		# 	#call mailer method for notifying users
  #   end
  # end

  # def import
  #    Product.import(params[:file])
  #   redirect_to temperatures_path, notice: "Thermometer imported."
  # end
  # GET /thermometers
  # GET /thermometers.json

	# def run
	# 	Rake::Task['thermometer:get_data'].reenable # in case you're going to invoke the same task second time.
	# 	Rake::Task['thermometer:get_data'].invoke
	# end

	# def email?
	# 	every(5.minutes) {}
	# end

  def index
    @thermometer = current_user.thermometers.order('created_at desc')
     if current_user.admin == true
      @user_type = "Admin"
      current_user.add_role "admin"
    else
      @user_type = "Non-Admin"
    end
  end

	def monitor
		puts "hello"
		# if @reading > @thermometer.max_temp
		# 	ThermometerMailer.max_thermo_violation
		# end
	end

  # GET /thermometers/1
  # GET /thermometers/1.json
  def show
		@thermometer = Thermometer.find(params[:id])
		respond_to do |format|
			format.html
			format.json
		end
  end

  # GET /thermometers/new
  def new
    # authorize! :edit, @thermometer
    @thermometer = Thermometer.new
		# 1.times @thermometer.reading.build
  end

  # GET /thermometers/1/edit
  def edit
     @thermometer = Thermometer.find(params[:id])
    authorize! :edit, @thermometer
  end

  # POST /thermometers
  # POST /thermometers.json
  def create
		puts "*"*50
		puts params
    @thermometer = current_user.thermometers.new(thermometer_params)

    respond_to do |format|
      if @thermometer.save
				# @thermometer.hello
				ThermometerMailer.thermo_confirmation(@thermometer).deliver
				# @thermometer.thermo_max_violation
        format.html { redirect_to @thermometer, notice: 'Thermometer was successfully created.' }
        format.json { render :show, status: :created, location: @thermometer }
				format.js
      else
        format.html { render :new }
        format.json { render json: @thermometer.errors, status: :unprocessable_entity }
			end
		endlfjhaefj
  end

  # PATCH/PUT /thermometers/1
  # PATCH/PUT /thermometers/1.json
  def update
    respond_to do |format|
      if @thermometer.update(thermometer_params)
        format.html { redirect_to @thermometer, notice: 'Thermometer was successfully updated.' }
        format.json { render :show, status: :ok, location: @thermometer }
      else
        format.html { render :edit }
        format.json { render json: @thermometer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /thermometers/1
  # DELETE /thermometers/1.json
  def destroy
    @thermometer.destroy
		puts "*" *50
		puts @thermometer
     # UserMailer.email_update_destroy(@users).deliver
    respond_to do |format|
      format.html { redirect_to thermometers_url, notice: 'Thermometer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_thermometer
      @thermometer = Thermometer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def thermometer_params
      params.require(:thermometer).permit(:name, :temperature, :email, :max_temp, :update_thermo, :reading_id)
    end
end

app/views/thermometers/_form.html.erb
<%= form_for(@thermometer, remote: :true) do |f| %>
  <% if @thermometer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@thermometer.errors.count, "error") %> prohibited this thermometer from being saved:</h2>

      <ul>
      <% @thermometer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="t_name">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
    <div class="t_name">
      <%= f.label :email %><br>
      <%= f.text_field :email %>
    </div>
    <div class="t_name">
      <%= f.label :max_temp %><br>
      <%= f.text_field :max_temp %>
    </div>



<div>Would you like to receive email updates? <%= f.check_box :update_thermo%> </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/thermometers/index.html.erb
<h1>Listing thermometers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Temperature</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <% if @thermometer.name %>
      <% @thermometer.each do |thermometer| %>
          <tr>
            <td><%= thermometer.name %></td>
            <td><%= link_to 'Show', thermometer %></td>
            <td><%= link_to 'Edit', edit_thermometer_path(thermometer) %></td>
            <td><%= link_to 'Destroy', thermometer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
      <% end %>
      </tbody>
      </table>
      <tbody>
  <!-- Button trigger modal -->
  <button class="btn btn-link" data-toggle="modal" data-target="#todo-<%= @thermometer.name %>-notes">
    View notes
  </button>

  <!-- Modal -->
  <div class="modal fade" id="todo-<%= @thermometer.name %>-notes" tabindex="-1" role="dialog" aria-labelledby="todo-<%= @thermometer.name %>-label" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h4 class="modal-title" id="todo-<%= @thermometer.name %>-label">Notes</h4>
        </div>
        <div class="modal-body">
          <%= @thermometer.name %>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-primary" data-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
  </div>
  <% end %>

</div>

<br>

<%= link_to 'New Thermometer', new_thermometer_path %>

<h2> Import Thermometer Data

app/views/thermometers/new.html.erb
<h1>New thermometer</h1>

<%= render 'form' %>

<%= link_to 'Back', thermometers_path %>

app/views/thermometers/show.html.erb
<p id="notice"><%= notice %></p>


<p>
  <strong>Name:</strong>
  <%= @thermometer.name %>
</p>



<%= link_to 'Edit', edit_thermometer_path %> |
<%= link_to 'Back', thermometers_path %>